# Theme settings
doks:
    baseurl:
    color_theme: purple # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: BitBadges
            image:
        nav:
            - item_name: About
              item_url: '#'
            - item_name: Vision
              item_url: '#'
            - item_name: Use Cases
              item_url: '#'
            - item_name: Database Schema
              item_url: '#'
            - item_name: The Repositories
              item_url: '#'
            - item_name: API Documentation
              item_url: '#'              
    footer:
        content:
            logo:
                text: BitBadges
                image:
            copyright: Copyright &copy; 2021. - BitBadges <br>All rights reserved.
        social_list:
            - network_name: facebook
              profile_url: 'https://www.facebook.com/hashtag/BitBadges'
            - network_name: twitter
              profile_url: 'https://twitter.com/hashtag/BitBadges?src=hashtag_click'
            - network_name: instagram
              profile_url: 'https://www.instagram.com/explore/tags/BitBadges'
            - network_name: youtube
              profile_url: 'https://www.youtube.com/results?search_query=BitBadges'
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
